// Priority tiers for zoom-based level-of-detail (LOD):
//   1 = always visible  (~13 major reference cities)
//   2 = medium zoom     (camera z < 4.2)
//   3 = close zoom      (camera z < 3.2)
//
// type: 'capital' | 'city'  — used for visual distinction on the globe

export const CAPITALS = [
  // Americas
  { city: 'Washington D.C.', lat: 38.89,  lon: -77.04,  priority: 1, type: 'capital' },
  { city: 'Ottawa',          lat: 45.42,  lon: -75.70,  priority: 2, type: 'capital' },
  { city: 'Mexico City',     lat: 19.43,  lon: -99.13,  priority: 1, type: 'capital' },
  { city: 'Havana',          lat: 23.13,  lon: -82.38,  priority: 3, type: 'capital' },
  { city: 'Bogotá',          lat:  4.71,  lon: -74.07,  priority: 2, type: 'capital' },
  { city: 'Lima',            lat: -12.05, lon: -77.04,  priority: 2, type: 'capital' },
  { city: 'Brasília',        lat: -15.78, lon: -47.93,  priority: 1, type: 'capital' },
  { city: 'Buenos Aires',    lat: -34.61, lon: -58.38,  priority: 2, type: 'capital' },
  { city: 'Santiago',        lat: -33.46, lon: -70.65,  priority: 2, type: 'capital' },
  { city: 'Caracas',         lat: 10.48,  lon: -66.88,  priority: 3, type: 'capital' },
  // Europe
  { city: 'London',          lat: 51.51,  lon:  -0.13,  priority: 1, type: 'capital' },
  { city: 'Paris',           lat: 48.85,  lon:   2.35,  priority: 1, type: 'capital' },
  { city: 'Berlin',          lat: 52.52,  lon:  13.41,  priority: 1, type: 'capital' },
  { city: 'Rome',            lat: 41.90,  lon:  12.48,  priority: 2, type: 'capital' },
  { city: 'Madrid',          lat: 40.42,  lon:  -3.70,  priority: 2, type: 'capital' },
  { city: 'Lisbon',          lat: 38.72,  lon:  -9.14,  priority: 3, type: 'capital' },
  { city: 'Amsterdam',       lat: 52.37,  lon:   4.90,  priority: 3, type: 'capital' },
  { city: 'Brussels',        lat: 50.85,  lon:   4.35,  priority: 3, type: 'capital' },
  { city: 'Bern',            lat: 46.95,  lon:   7.45,  priority: 3, type: 'capital' },
  { city: 'Vienna',          lat: 48.21,  lon:  16.37,  priority: 2, type: 'capital' },
  { city: 'Prague',          lat: 50.09,  lon:  14.42,  priority: 3, type: 'capital' },
  { city: 'Warsaw',          lat: 52.23,  lon:  21.01,  priority: 2, type: 'capital' },
  { city: 'Budapest',        lat: 47.50,  lon:  19.04,  priority: 3, type: 'capital' },
  { city: 'Bucharest',       lat: 44.43,  lon:  26.10,  priority: 3, type: 'capital' },
  { city: 'Athens',          lat: 37.98,  lon:  23.73,  priority: 2, type: 'capital' },
  { city: 'Kyiv',            lat: 50.45,  lon:  30.52,  priority: 2, type: 'capital' },
  { city: 'Moscow',          lat: 55.75,  lon:  37.62,  priority: 1, type: 'capital' },
  { city: 'Minsk',           lat: 53.90,  lon:  27.57,  priority: 3, type: 'capital' },
  { city: 'Stockholm',       lat: 59.33,  lon:  18.07,  priority: 2, type: 'capital' },
  { city: 'Oslo',            lat: 59.91,  lon:  10.75,  priority: 2, type: 'capital' },
  { city: 'Helsinki',        lat: 60.17,  lon:  24.94,  priority: 3, type: 'capital' },
  { city: 'Copenhagen',      lat: 55.68,  lon:  12.57,  priority: 3, type: 'capital' },
  { city: 'Reykjavik',       lat: 64.13,  lon: -21.94,  priority: 2, type: 'capital' },
  // Middle East / Central Asia
  { city: 'Ankara',          lat: 39.93,  lon:  32.86,  priority: 2, type: 'capital' },
  { city: 'Riyadh',          lat: 24.69,  lon:  46.72,  priority: 2, type: 'capital' },
  { city: 'Baghdad',         lat: 33.34,  lon:  44.40,  priority: 2, type: 'capital' },
  { city: 'Tehran',          lat: 35.69,  lon:  51.39,  priority: 2, type: 'capital' },
  { city: 'Kabul',           lat: 34.53,  lon:  69.17,  priority: 3, type: 'capital' },
  { city: 'Islamabad',       lat: 33.72,  lon:  73.06,  priority: 2, type: 'capital' },
  { city: 'Amman',           lat: 31.95,  lon:  35.93,  priority: 3, type: 'capital' },
  { city: 'Beirut',          lat: 33.89,  lon:  35.50,  priority: 3, type: 'capital' },
  { city: 'Doha',            lat: 25.29,  lon:  51.53,  priority: 3, type: 'capital' },
  { city: 'Abu Dhabi',       lat: 24.45,  lon:  54.38,  priority: 3, type: 'capital' },
  { city: 'Muscat',          lat: 23.59,  lon:  58.59,  priority: 3, type: 'capital' },
  { city: 'Baku',            lat: 40.41,  lon:  49.87,  priority: 3, type: 'capital' },
  { city: 'Tbilisi',         lat: 41.69,  lon:  44.83,  priority: 3, type: 'capital' },
  { city: 'Tashkent',        lat: 41.30,  lon:  69.24,  priority: 3, type: 'capital' },
  { city: 'Nur-Sultan',      lat: 51.18,  lon:  71.45,  priority: 3, type: 'capital' },
  { city: 'Ulaanbaatar',     lat: 47.91,  lon: 106.88,  priority: 3, type: 'capital' },
  // Africa
  { city: 'Cairo',           lat: 30.06,  lon:  31.24,  priority: 1, type: 'capital' },
  { city: 'Algiers',         lat: 36.74,  lon:   3.06,  priority: 2, type: 'capital' },
  { city: 'Rabat',           lat: 34.02,  lon:  -6.84,  priority: 3, type: 'capital' },
  { city: 'Abuja',           lat:  9.05,  lon:   7.53,  priority: 3, type: 'capital' },
  { city: 'Accra',           lat:  5.56,  lon:  -0.20,  priority: 3, type: 'capital' },
  { city: 'Nairobi',         lat: -1.29,  lon:  36.82,  priority: 1, type: 'capital' },
  { city: 'Addis Ababa',     lat:  9.03,  lon:  38.74,  priority: 2, type: 'capital' },
  { city: 'Kinshasa',        lat: -4.32,  lon:  15.32,  priority: 3, type: 'capital' },
  { city: 'Pretoria',        lat: -25.74, lon:  28.19,  priority: 2, type: 'capital' },
  { city: 'Khartoum',        lat: 15.55,  lon:  32.53,  priority: 3, type: 'capital' },
  // Asia / Pacific
  { city: 'New Delhi',       lat: 28.61,  lon:  77.21,  priority: 1, type: 'capital' },
  { city: 'Dhaka',           lat: 23.72,  lon:  90.41,  priority: 2, type: 'capital' },
  { city: 'Kathmandu',       lat: 27.70,  lon:  85.32,  priority: 3, type: 'capital' },
  { city: 'Beijing',         lat: 39.91,  lon: 116.39,  priority: 1, type: 'capital' },
  { city: 'Tokyo',           lat: 35.68,  lon: 139.69,  priority: 1, type: 'capital' },
  { city: 'Seoul',           lat: 37.57,  lon: 126.98,  priority: 2, type: 'capital' },
  { city: 'Taipei',          lat: 25.05,  lon: 121.56,  priority: 3, type: 'capital' },
  { city: 'Bangkok',         lat: 13.75,  lon: 100.52,  priority: 2, type: 'capital' },
  { city: 'Hanoi',           lat: 21.03,  lon: 105.83,  priority: 3, type: 'capital' },
  { city: 'Jakarta',         lat: -6.21,  lon: 106.85,  priority: 2, type: 'capital' },
  { city: 'Manila',          lat: 14.60,  lon: 120.98,  priority: 3, type: 'capital' },
  { city: 'Kuala Lumpur',    lat:  3.14,  lon: 101.69,  priority: 3, type: 'capital' },
  { city: 'Singapore',       lat:  1.35,  lon: 103.82,  priority: 2, type: 'capital' },
  { city: 'Canberra',        lat: -35.28, lon: 149.13,  priority: 2, type: 'capital' },
  { city: 'Wellington',      lat: -41.29, lon: 174.78,  priority: 2, type: 'capital' },
  { city: 'Phnom Penh',      lat: 11.56,  lon: 104.92,  priority: 3, type: 'capital' },
  { city: 'Yangon',          lat: 16.87,  lon:  96.19,  priority: 3, type: 'capital' },
  { city: 'Colombo',         lat:  6.92,  lon:  79.85,  priority: 3, type: 'capital' },
];

// Major non-capital cities — shown on top of capitals in LAYER_CITIES mode
export const MAJOR_CITIES = [
  { city: 'New York',        lat: 40.71,  lon: -74.01,  priority: 1, type: 'city' },
  { city: 'Los Angeles',     lat: 34.05,  lon: -118.24, priority: 2, type: 'city' },
  { city: 'Chicago',         lat: 41.85,  lon: -87.65,  priority: 2, type: 'city' },
  { city: 'Toronto',         lat: 43.65,  lon: -79.38,  priority: 2, type: 'city' },
  { city: 'Vancouver',       lat: 49.25,  lon: -123.12, priority: 3, type: 'city' },
  { city: 'São Paulo',       lat: -23.55, lon: -46.63,  priority: 1, type: 'city' },
  { city: 'Rio de Janeiro',  lat: -22.91, lon: -43.17,  priority: 2, type: 'city' },
  { city: 'Istanbul',        lat: 41.01,  lon:  28.96,  priority: 2, type: 'city' },
  { city: 'Milan',           lat: 45.46,  lon:   9.19,  priority: 2, type: 'city' },
  { city: 'Barcelona',       lat: 41.39,  lon:   2.15,  priority: 2, type: 'city' },
  { city: 'Munich',          lat: 48.14,  lon:  11.58,  priority: 3, type: 'city' },
  { city: 'Hamburg',         lat: 53.55,  lon:   9.99,  priority: 3, type: 'city' },
  { city: 'Frankfurt',       lat: 50.11,  lon:   8.68,  priority: 3, type: 'city' },
  { city: 'Lagos',           lat:  6.52,  lon:   3.38,  priority: 2, type: 'city' },
  { city: 'Casablanca',      lat: 33.57,  lon:  -7.59,  priority: 3, type: 'city' },
  { city: 'Cape Town',       lat: -33.92, lon:  18.42,  priority: 2, type: 'city' },
  { city: 'Johannesburg',    lat: -26.20, lon:  28.04,  priority: 2, type: 'city' },
  { city: 'Dar es Salaam',   lat: -6.79,  lon:  39.20,  priority: 3, type: 'city' },
  { city: 'Dubai',           lat: 25.20,  lon:  55.27,  priority: 1, type: 'city' },
  { city: 'Karachi',         lat: 24.86,  lon:  67.01,  priority: 2, type: 'city' },
  { city: 'Mumbai',          lat: 19.08,  lon:  72.88,  priority: 1, type: 'city' },
  { city: 'Kolkata',         lat: 22.57,  lon:  88.36,  priority: 2, type: 'city' },
  { city: 'Bangalore',       lat: 12.97,  lon:  77.59,  priority: 2, type: 'city' },
  { city: 'Chennai',         lat: 13.08,  lon:  80.27,  priority: 3, type: 'city' },
  { city: 'Shanghai',        lat: 31.23,  lon: 121.47,  priority: 1, type: 'city' },
  { city: 'Guangzhou',       lat: 23.13,  lon: 113.26,  priority: 2, type: 'city' },
  { city: 'Shenzhen',        lat: 22.54,  lon: 114.06,  priority: 3, type: 'city' },
  { city: 'Chengdu',         lat: 30.66,  lon: 104.07,  priority: 3, type: 'city' },
  { city: 'Wuhan',           lat: 30.59,  lon: 114.31,  priority: 3, type: 'city' },
  { city: 'Osaka',           lat: 34.69,  lon: 135.50,  priority: 2, type: 'city' },
  { city: 'Busan',           lat: 35.10,  lon: 129.04,  priority: 3, type: 'city' },
  { city: 'Sydney',          lat: -33.87, lon: 151.21,  priority: 1, type: 'city' },
  { city: 'Melbourne',       lat: -37.81, lon: 144.96,  priority: 2, type: 'city' },
];
